server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: demo
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/gpone_db}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_PASSWORD:root}
    password: ${DBMS_USERNAME:rootpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "Z0pRqZV/Ljn7X+6N905zG0Tbi9zIoLMcVHNRVqFpGdBXY5VI+Aodk8fSPUXNYsUo"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds