server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: demo
  datasource:
    url: "jdbc:mysql://localhost:3306/gpone_db"
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true